In [22]:
import  pandas as pd

In [23]:

gedi = pd.read_csv("../data/CSV/gedi.csv")
sentinel_1 = pd.read_csv("../data/CSV/sentinel_1.csv")
sentinel_2 = pd.read_csv("../data/CSV/sentinel_2.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/CSV/gedi.csv'

In [ ]:
gedi

                x          y  spatial_ref  rh98  rh100        time
0       43.133013  14.736638            0   NaN    NaN  2019-04-01
1       43.133013  14.736548            0   NaN    NaN  2019-04-01
2       43.133013  14.736458            0   NaN    NaN  2019-04-01
3       43.133013  14.736368            0   NaN    NaN  2019-04-01
4       43.133013  14.736278            0   NaN    NaN  2019-04-01
...           ...        ...          ...   ...    ...         ...
617710  43.156728  14.713820            0   NaN    NaN  2019-12-01
617711  43.156728  14.713731            0   NaN    NaN  2019-12-01
617712  43.156728  14.713641            0   NaN    NaN  2019-12-01
617713  43.156728  14.713551            0   NaN    NaN  2019-12-01
617714  43.156728  14.713461            0   NaN    NaN  2019-12-01

[617715 rows x 6 columns]

In [ ]:
merged_data_1 = pd.merge(sentinel_2, sentinel_1,on=['time', 'x', 'y'], how='outer')

In [ ]:
gedi['time'] = pd.to_datetime(gedi['time'])

# Extraire uniquement la date
gedi['time1'] =gedi['time'].dt.date

In [ ]:
merged_data = pd.merge(merged_data_1, gedi,on=['time', 'x', 'y'], how='outer')
merged_data

ValueError: You are trying to merge on object and datetime64[ns] columns for key 'time'. If you wish to proceed you should use pd.concat

In [ ]:
merged_data = merged_data.dropna(subset=['rh98'], axis=0)

merged_data

,time,x,y,spatial_ref_x,B1,B2,B3,B4,B5,B6,...,QA10,QA20,QA60,spatial_ref_y,VV,VH,angle,spatial_ref,rh98,rh100
69517,2019-05-01,43.133282,14.722893,0,0.11810,0.1436,0.1980,0.2579,0.28650,0.28455,...,0.0,0.0,0.0,0,-26.111400,-29.975774,40.656174,0,2.47,3.18
69518,2019-05-01,43.133282,14.722983,0,0.11810,0.1438,0.1997,0.2589,0.28650,0.28455,...,0.0,0.0,0.0,0,-26.658973,-42.396477,40.656290,0,2.47,3.18
69776,2019-05-01,43.133372,14.722893,0,0.11810,0.1452,0.1990,0.2577,0.28650,0.28455,...,0.0,0.0,0.0,0,-24.532608,-31.742374,40.656723,0,2.47,3.18
69777,2019-05-01,43.133372,14.722983,0,0.11810,0.1437,0.1963,0.2577,0.28650,0.28455,...,0.0,0.0,0.0,0,-27.305188,-42.055486,40.656837,0,2.47,3.18
70035,2019-05-01,43.133462,14.722893,0,0.11700,0.1430,0.1989,0.2585,0.28700,0.28465,...,0.0,0.0,0.0,0,-23.288867,-37.264314,40.657272,0,2.47,3.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480130,2019-10-01,43.156638,14.731697,0,0.09555,0.1211,0.1759,0.2407,0.26850,0.27165,...,0.0,0.0,0.0,0,-19.847282,-29.566361,38.809494,0,2.76,3.55
480131,2019-10-01,43.156638,14.731787,0,0.09555,0.1193,0.1738,0.2358,0.26850,0.27165,...,0.0,0.0,0.0,0,-18.581744,-27.462784,38.809610,0,2.76,3.55
480383,2019-10-01,43.156728,14.731158,0,0.09455,0.1244,0.1816,0.2440,0.27495,0.27650,...,0.0,0.0,0.0,0,-20.890253,-29.349246,38.808765,0,2.54,3.29
480384,2019-10-01,43.156728,14.731248,0,0.09455,0.1236,0.1795,0.2440,0.27495,0.27650,...,0.0,0.0,0.0,0,-21.794770,-32.179702,38.808884,0,2.54,3.29
480385,2019-10-01,43.156728,14.731338,0,0.09555,0.1284,0.1831,0.2500,0.26755,0.27070,...,0.0,0.0,0.0,0,-21.769242,-31.497450,38.809002,0,2.54,3.29

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/Data_Collection_and_Processing/gedi_output.nc/gedi.csv')

In [ ]:
df.isnull().sum()

x              0
y              0
spatial_ref    0
rh98           0
rh100          0
time           0
dtype: int64

In [ ]:
df = pd.read_csv('/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/test/gedi_2019.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/test/gedi_2019.csv'

In [ ]:
len(df.shape)

2

In [ ]:
df1 =pd.read_csv('/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/test/sentinel_1_2019.csv')
df1.

(617715, 7)

In [ ]:
df2 = pd.read_csv("/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/test/test.csv")
#df3 = df2.dropna(subset=["rh98"], axis=1)

In [ ]:
df2.

,Unnamed: 0,time,x,y,spatial_ref,rh98,rh100,time.1,x.1,y.1,...,TCI_G,TCI_B,MSK_CLDPRB,MSK_SNWPRB,QA10,QA20,QA60,MSK_CLASSI_OPAQUE,MSK_CLASSI_CIRRUS,MSK_CLASSI_SNOW_ICE
0,0,2019-05-01 08:00:00,43.133013,14.736638,0,NaN,NaN,2019-05-01,43.133013,14.736638,...,0.01920,0.01410,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,1,2019-05-01 08:00:00,43.133013,14.736548,0,NaN,NaN,2019-05-01,43.133013,14.736548,...,0.01920,0.01420,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,2,2019-05-01 08:00:00,43.133013,14.736458,0,NaN,NaN,2019-05-01,43.133013,14.736458,...,0.01950,0.01400,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,3,2019-05-01 08:00:00,43.133013,14.736368,0,NaN,NaN,2019-05-01,43.133013,14.736368,...,0.01950,0.01410,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,4,2019-05-01 08:00:00,43.133013,14.736278,0,NaN,NaN,2019-05-01,43.133013,14.736278,...,0.01960,0.01450,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137265,68630,2019-10-01 08:00:00,43.156728,14.713820,0,NaN,NaN,2019-10-01,43.156728,14.713820,...,0.01890,0.01290,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
137266,68631,2019-10-01 08:00:00,43.156728,14.713731,0,NaN,NaN,2019-10-01,43.156728,14.713731,...,0.01895,0.01300,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
137267,68632,2019-10-01 08:00:00,43.156728,14.713641,0,NaN,NaN,2019-10-01,43.156728,14.713641,...,0.01865,0.01275,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
137268,68633,2019-10-01 08:00:00,43.156728,14.713551,0,NaN,NaN,2019-10-01,43.156728,14.713551,...,0.01850,0.01255,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
137269,68634,2019-10-01 08:00:00,43.156728,14.713461,0,NaN,NaN,2019-10-01,43.156728,14.713461,...,0.01875,0.01295,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [ ]:
df2['rh100'].unique()

array([        nan,  3.18000007,  3.4000001 ,  3.22000003,  3.32999992,
        3.0999999 ,  3.36999989,  3.25      ,  2.92000008,  3.1400001 ,
        2.95000005,  3.28999996,  3.44000006,  3.02999997,  3.05999994,
        3.70000005,  3.50999999,  4.1500001 ,  5.69000006,  4.07999992,
        3.51999998,  2.99000001,  2.88000011,  3.80999994,  4.53000021,
        3.8499999 , 15.5       ,  3.8900001 ,  3.06999993,  4.19000006,
        5.94999981,  3.58999991,  4.        ,  3.48000002,  4.40999985,
        3.93000007,  2.76999998,  3.66000009,  2.83999991,  3.63000011,
        3.74000001,  4.48000002,  3.92000008,  4.67000008,  4.78000021,
        4.36999989,  3.76999998,  4.17999983,  3.17000008,  4.21999979,
        3.88000011,  3.54999995,  4.75      ,  4.03000021,  4.63000011,
        4.86000013,  3.21000004,  3.47000003,  4.51999998,  3.31999993,
        7.36000013,  5.07999992,  3.3599999 ,  3.61999989,  4.44999981,
        4.82000017,  5.30999994,  4.71000004,  5.03999996,  5.01000023,
        4.07000017, 25.57999992,  4.32999992, 14.47000027, 15.26000023,
        5.38000011,  3.73000002,  3.57999992,  4.11000013,  3.43000007])

In [ ]:
import pandas as pd 

df = pd.read_csv("/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/Data_Collection_and_Processing/src/Combined_Data.csv")

In [ ]:

# Transformer 'Region_1' à 'Region_400' en 'Region_401' à 'Region_800'
df['polygon'] = df['polygon'].str.replace('polygon_', '').astype(int) + 400
df['polygon'] = 'polygon_' + df['polygon'].astype(str) # Affiche les premières lignes pour vérifier le renommage

In [ ]:
df.to_csv("test.csv", index=False)

In [ ]:
df1 = pd.read_csv("/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/Data_Collection_and_Processing/data/CSV/Combined_Data.csv")
df1.shape

(214747, 44)

In [ ]:
df2 = pd.read_csv("/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/Data_Collection_and_Processing/notebook/test.csv")
df2.shape

(271081, 44)

In [ ]:
concat = pd.concat([df1, df2])

In [ ]:
concat.to_csv("data_dframe_gedi_s1_and_s2.csv", index=False)

In [ ]:
import pandas as pd

In [ ]:
cv =pd.read_csv("/Users/clementkm/Documents/School/TOLBI STAGE /PROJECT/Data_Collection_and_Processing/data/CSV/data_dframe_gedi_s1_and_s2.csv")
cv.shape

(485828, 44)

In [ ]:
cv

,time,x,y,spatial_ref,rh98,rh100,time.1,x.1,y.1,spatial_ref.1,...,TCI_B,MSK_CLDPRB,MSK_SNWPRB,QA10,QA20,QA60,MSK_CLASSI_OPAQUE,MSK_CLASSI_CIRRUS,MSK_CLASSI_SNOW_ICE,polygon
0,2020-05-01 08:00:00,45.691055,34.259454,0,3.880000,5.82,2020-05-01,45.691055,34.259454,0,...,0.0201,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_1
1,2020-05-01 08:00:00,45.691055,34.259364,0,3.880000,5.82,2020-05-01,45.691055,34.259364,0,...,0.0214,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_1
2,2020-05-01 08:00:00,45.691415,34.259724,0,18.370001,21.40,2020-05-01,45.691415,34.259724,0,...,0.0145,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_1
3,2020-05-01 08:00:00,45.691415,34.259634,0,18.370001,21.40,2020-05-01,45.691415,34.259634,0,...,0.0130,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_1
4,2020-05-01 08:00:00,45.691415,34.259544,0,18.370001,21.40,2020-05-01,45.691415,34.259544,0,...,0.0129,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485823,2020-10-01 08:00:00,9.764193,35.195589,0,2.390000,3.52,2020-10-01,9.764193,35.195589,0,...,0.0154,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_737
485824,2020-10-01 08:00:00,9.764283,35.213555,0,2.470000,3.52,2020-10-01,9.764283,35.213555,0,...,0.0098,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_737
485825,2020-10-01 08:00:00,9.764283,35.213465,0,2.470000,3.52,2020-10-01,9.764283,35.213465,0,...,0.0094,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_737
485826,2020-10-01 08:00:00,9.764283,35.195499,0,2.540000,3.44,2020-10-01,9.764283,35.195499,0,...,0.0161,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_737
485827,2020-10-01 08:00:00,9.764283,35.195409,0,2.540000,3.44,2020-10-01,9.764283,35.195409,0,...,0.0154,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,polygon_737

In [ ]:
cv.isnull().sum()

time                        0
x                           0
y                           0
spatial_ref                 0
rh98                        0
rh100                       0
time.1                      0
x.1                         0
y.1                         0
spatial_ref.1               0
VV                        142
VH                        142
angle                       0
time.2                      0
x.2                         0
y.2                         0
spatial_ref.2               0
B1                        898
B2                        815
B3                        820
B4                        815
B5                        815
B6                        821
B7                        821
B8                        815
B8A                       823
B9                        812
B11                       815
B12                       815
AOT                       815
WVP                       815
SCL                       815
TCI_R                     817
TCI_G                     830
TCI_B                     916
MSK_CLDPRB                787
MSK_SNWPRB                787
QA10                      787
QA20                      787
QA60                      787
MSK_CLASSI_OPAQUE      485828
MSK_CLASSI_CIRRUS      485828
MSK_CLASSI_SNOW_ICE    485828
polygon                     0
dtype: int64

In [ ]:
cv.columns

Index(['time', 'x', 'y', 'spatial_ref', 'rh98', 'rh100', 'time.1', 'x.1',
       'y.1', 'spatial_ref.1', 'VV', 'VH', 'angle', 'time.2', 'x.2', 'y.2',
       'spatial_ref.2', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A',
       'B9', 'B11', 'B12', 'AOT', 'WVP', 'SCL', 'TCI_R', 'TCI_G', 'TCI_B',
       'MSK_CLDPRB', 'MSK_SNWPRB', 'QA10', 'QA20', 'QA60', 'MSK_CLASSI_OPAQUE',
       'MSK_CLASSI_CIRRUS', 'MSK_CLASSI_SNOW_ICE', 'polygon'],
      dtype='object')

In [ ]:
import ee
cloud_project = 'ee-ckafwimbi'

try:
        ee.Initialize(project=cloud_project)
except:
        ee.Authenticate()
        ee.Initialize(project=cloud_project)

EEException: Caller does not have required permission to use project ee-ckafwimbi. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=ee-ckafwimbi and then retry. Propagation of the new permission may take a few minutes.

In [ ]:
cv.clip(2)

TypeError: '>=' not supported between instances of 'str' and 'int'

In [ ]:
import geopandas as gpd

In [39]:
data = gpd.read_file('/Users/clementkm/Documents/JOBS/TOLBI/data/data_collection_mission_arachide_casamance_2024.geojson')

In [40]:
data = data.rename(columns={"Veuillez choisir la culture trouvée": "Renseigner la culture"})

In [41]:
data['Zone'] = "Casamance"

In [42]:
data.columns

Index(['fid', 'Nom de l'enqueteur', 'Prenom de l'enqueteur',
       'Telephone de l'enqueteur', 'Renseigner la culture', '_id_record',
       'Si autre, entrez le nom de la culture', 'Surface en ha', 'layer',
       'path', 'geometry', 'Zone'],
      dtype='object')

In [ ]:
data.to_file("../data/data_collection_mission_arachide_casamance_2024", driver="GeoJSON")

In [43]:
data = data.drop(['layer', 'path'], axis=1)

In [44]:
data.head()

,fid,Nom de l'enqueteur,Prenom de l'enqueteur,Telephone de l'enqueteur,Renseigner la culture,_id_record,"Si autre, entrez le nom de la culture",Surface en ha,geometry,Zone
0,1,Ndiaye,Ousseynou,774959377,arachide,362,None,NaN,"POLYGON ((-15.19598 13.26442, -15.19598 13.264...",Casamance
1,2,SABALY,Issaga,772495133,niébé,377,None,NaN,"POLYGON ((-14.05558 13.16426, -14.05566 13.164...",Casamance
2,3,Ndiaye,Ousseynou,774959377,arachide,354,None,NaN,"POLYGON ((-15.20357 13.25673, -15.20357 13.256...",Casamance
3,4,Ndiaye,Ousseynou,774959377,arachide,355,None,NaN,"POLYGON ((-15.20338 13.25658, -15.20338 13.256...",Casamance
4,5,Ndiaye,Ousseynou,774959377,arachide,356,None,NaN,"POLYGON ((-15.20336 13.25658, -15.20319 13.256...",Casamance

In [45]:

data["Renseigner la culture"] = data["Renseigner la culture"].str.lower()
new_data = data

In [46]:
new_data["Renseigner la culture"].value_counts()

Renseigner la culture
arachide                            1693
autre                                225
maïs                                 126
mil                                   75
herbres                               73
arachide+niébé                        57
niébé                                 40
riz                                   19
sorgho                                17
oseille                               13
arachide+mil                          12
arachide+oseille                      11
mil, arachide                          8
arachide, oseille                      5
arachide+maïs                          4
arachide, autre                        3
arachide, mil                          3
arachide, riz                          2
arachide+oseille, arachide+niébé       1
niébé, autre                           1
mil, maïs                              1
sorgho, maïs                           1
autre, arachide                        1
arachide+niébé, herbres, oseille       1
                                       1
maïs, mil                              1
arachide+sorgho                        1
arachide, herbres                      1
Name: count, dtype: int64

In [48]:
new_data.to_file('../data/data_collection_mission_arachide_casamance_2024.geojson', driver="GeoJSON")

In [49]:
data_collection_kaolack = gpd.read_file('../data/INTERNE/map (2).geojson')

In [51]:
data_collection_kaolack['Zone']="Kaolack"

In [53]:
data_collection_kaolack["Renseigner la culture"].value_counts()

Renseigner la culture
arachide          78
mil               24
arachide+mil      12
maïs               8
arachide+niébé     7
niébé              3
Name: count, dtype: int64

In [ ]:
data_collection_kaolack.to_file('../data/INTERNE/data_collection_mission_arachide_kaolack_.geojson',driver="GeoJSON")

In [56]:
import pandas as pd

In [68]:
casamance = gpd.read_file('../data/INTERNE/data_collection_mission_arachide_casamance_2024.geojson')
kaolack = gpd.read_file('../data/INTERNE/data_collection_mission_arachide_kaolack_.geojson')

kaolack.columns

Index(['avatar', 'Nom de l'enqueteur', 'Prenom de l'enqueteur',
       'Renseigner la culture', 'Telephone de l'enqueteur',
       'Décricez l'état de santé des cultures dans la zone-',
       'Donner une approximation du pourcentage d"herbes dans la zone',
       'Quelle est la phénologie actuelle de la culture dans la zone?',
       'Veuillez renseigner la culture présente (si c'est mixte renseigner les cultures présente dans la zone)-',
       '_id_record', 'Zone', 'geometry'],
      dtype='object')

In [67]:
casamance.columns

Index(['fid', 'Nom de l'enqueteur', 'Prenom de l'enqueteur',
       'Telephone de l'enqueteur', 'Renseigner la culture', '_id_record',
       'Si autre, entrez le nom de la culture', 'Surface en ha', 'Zone',
       'geometry'],
      dtype='object')

In [70]:
colonnes_communes = ["Nom de l'enqueteur", "Prenom de l'enqueteur",
       "Renseigner la culture", "Telephone de l'enqueteur","_id_record", "Zone", "geometry"]

In [73]:
combined_gdf = casamance.merge(kaolack, on=colonnes_communes, how='inner')

In [74]:
combined_gdf

Empty GeoDataFrame
Columns: [fid, Nom de l'enqueteur, Prenom de l'enqueteur, Telephone de l'enqueteur, Renseigner la culture, _id_record, Si autre, entrez le nom de la culture, Surface en ha, Zone, geometry, avatar, Décricez l'état de santé des cultures dans la zone-, Donner une approximation du pourcentage d"herbes dans la zone, Quelle est la phénologie actuelle de la culture dans la zone?, Veuillez renseigner la culture présente (si c'est mixte renseigner les cultures présente dans la zone)-]
Index: []

In [93]:
combined = pd.concat([casamance,kaolack], ignore_index=True)
combined.dtypes

fid                                                                                                         float64
Nom de l'enqueteur                                                                                           object
Prenom de l'enqueteur                                                                                        object
Telephone de l'enqueteur                                                                                     object
Renseigner la culture                                                                                        object
_id_record                                                                                                    int32
Si autre, entrez le nom de la culture                                                                        object
Surface en ha                                                                                               float64
Zone                                                                                                         object
geometry                                                                                                   geometry
avatar                                                                                                       object
Décricez l'état de santé des cultures dans la zone-                                                          object
Donner une approximation du pourcentage d"herbes dans la zone                                                object
Quelle est la phénologie actuelle de la culture dans la zone?                                                object
Veuillez renseigner la culture présente (si c'est mixte renseigner les cultures présente dans la zone)-      object
dtype: object

In [94]:
combined.to_file("../data/INTERNE/data_collection_mission_arachide_2024.geojson", driver="GeoJSON")

In [92]:
# Convertir les colonnes entières en int16
casamance['fid'] = casamance['fid'].astype('int16')
casamance['_id_record'] = casamance['_id_record'].astype('int16')



# Vérifier les types de données après la conversion
print(casamance.dtypes)

fid                                         int16
Nom de l'enqueteur                         object
Prenom de l'enqueteur                      object
Telephone de l'enqueteur                   object
Renseigner la culture                      object
_id_record                                  int16
Si autre, entrez le nom de la culture      object
Surface en ha                             float64
Zone                                       object
geometry                                 geometry
dtype: object

In [103]:
rice_datase_1 = gpd.read_file('../../DATA GEOJSON/roi_st_louis.geojson')
rice_dataset_2 = gpd.read_file('../../DATA GEOJSON/rice_anambe.geojson')

dataset_rice = pd.concat([rice_datase_1 , rice_dataset_2])
dataset_rice["Renseigner la culture"] = "riz"

dataset_rice["_id_record"] = pd.RangeIndex(start=5300, stop=5300 + len(dataset_rice), step=1)
dataset_rice

,id,geometry,Renseigner la culture,_id_record
0,0,"POLYGON ((-16.26345 16.51086, -16.26285 16.511...",riz,5300
1,1,"POLYGON ((-16.26274 16.51123, -16.26225 16.511...",riz,5301
2,2,"POLYGON ((-16.26254 16.51083, -16.26205 16.511...",riz,5302
3,3,"POLYGON ((-16.26321 16.50828, -16.26274 16.508...",riz,5303
4,4,"POLYGON ((-16.27291 16.48602, -16.2726 16.4861...",riz,5304
...,...,...,...,...
57,57,"POLYGON ((-14.10851 12.98454, -14.10757 12.984...",riz,5430
58,58,"POLYGON ((-14.11904 12.93898, -14.11819 12.939...",riz,5431
59,59,"POLYGON ((-14.11862 12.93784, -14.11784 12.937...",riz,5432
60,60,"POLYGON ((-14.11506 12.93962, -14.11434 12.939...",riz,5433
61,61,"POLYGON ((-14.11346 12.93739, -14.11278 12.937...",riz,5434

In [ ]:
dataset_rice.to_file("../data/INTERNE/data_collection_mission_arachide_2024_(riz).geojson", driver="GeoJSON")

dataset_rice